package stanislav.volnjanskij.popularmovies.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import stanislav.volnjanskij.popularmovies.db.Trailer;
import stanislav.volnjanskij.popularmovies.db.Movie;

import stanislav.volnjanskij.popularmovies.db.TrailerDao;
import stanislav.volnjanskij.popularmovies.db.MovieDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trailerDaoConfig;
    private final DaoConfig movieDaoConfig;

    private final TrailerDao trailerDao;
    private final MovieDao movieDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trailerDaoConfig = daoConfigMap.get(TrailerDao.class).clone();
        trailerDaoConfig.initIdentityScope(type);

        movieDaoConfig = daoConfigMap.get(MovieDao.class).clone();
        movieDaoConfig.initIdentityScope(type);

        trailerDao = new TrailerDao(trailerDaoConfig, this);
        movieDao = new MovieDao(movieDaoConfig, this);

        registerDao(Trailer.class, trailerDao);
        registerDao(Movie.class, movieDao);
    }
    
    public void clear() {
        trailerDaoConfig.getIdentityScope().clear();
        movieDaoConfig.getIdentityScope().clear();
    }

    public TrailerDao getTrailerDao() {
        return trailerDao;
    }

    public MovieDao getMovieDao() {
        return movieDao;
    }

}
