package stanislav.volnjanskij.popularmovies.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRAILER".
 */
public class Trailer {

    private Long id;
    private String key;
    /** Not-null value. */
    private String name;
    private long movie_id;

    public Trailer() {
    }

    public Trailer(Long id) {
        this.id = id;
    }

    public Trailer(Long id, String key, String name, long movie_id) {
        this.id = id;
        this.key = key;
        this.name = name;
        this.movie_id = movie_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public long getMovie_id() {
        return movie_id;
    }

    public void setMovie_id(long movie_id) {
        this.movie_id = movie_id;
    }

}
