package stanislav.volnjanskij.popularmovies.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import stanislav.volnjanskij.popularmovies.db.Movie;
import stanislav.volnjanskij.popularmovies.db.Movie2;

import stanislav.volnjanskij.popularmovies.db.MovieDao;
import stanislav.volnjanskij.popularmovies.db.Movie2Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig movieDaoConfig;
    private final DaoConfig movie2DaoConfig;

    private final MovieDao movieDao;
    private final Movie2Dao movie2Dao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        movieDaoConfig = daoConfigMap.get(MovieDao.class).clone();
        movieDaoConfig.initIdentityScope(type);

        movie2DaoConfig = daoConfigMap.get(Movie2Dao.class).clone();
        movie2DaoConfig.initIdentityScope(type);

        movieDao = new MovieDao(movieDaoConfig, this);
        movie2Dao = new Movie2Dao(movie2DaoConfig, this);

        registerDao(Movie.class, movieDao);
        registerDao(Movie2.class, movie2Dao);
    }
    
    public void clear() {
        movieDaoConfig.getIdentityScope().clear();
        movie2DaoConfig.getIdentityScope().clear();
    }

    public MovieDao getMovieDao() {
        return movieDao;
    }

    public Movie2Dao getMovie2Dao() {
        return movie2Dao;
    }

}
