package stanislav.volnjanskij.popularmovies.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MOVIE2".
 */
public class Movie2 {

    private Long id;
    private String overview;
    private String poster_path;
    private String title;
    private String voteAvarage;
    private String releaseDate;
    private Integer runtime;
    private String cachedPosterPath;

    public Movie2() {
    }

    public Movie2(Long id) {
        this.id = id;
    }

    public Movie2(Long id, String overview, String poster_path, String title, String voteAvarage, String releaseDate, Integer runtime, String cachedPosterPath) {
        this.id = id;
        this.overview = overview;
        this.poster_path = poster_path;
        this.title = title;
        this.voteAvarage = voteAvarage;
        this.releaseDate = releaseDate;
        this.runtime = runtime;
        this.cachedPosterPath = cachedPosterPath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOverview() {
        return overview;
    }

    public void setOverview(String overview) {
        this.overview = overview;
    }

    public String getPoster_path() {
        return poster_path;
    }

    public void setPoster_path(String poster_path) {
        this.poster_path = poster_path;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getVoteAvarage() {
        return voteAvarage;
    }

    public void setVoteAvarage(String voteAvarage) {
        this.voteAvarage = voteAvarage;
    }

    public String getReleaseDate() {
        return releaseDate;
    }

    public void setReleaseDate(String releaseDate) {
        this.releaseDate = releaseDate;
    }

    public Integer getRuntime() {
        return runtime;
    }

    public void setRuntime(Integer runtime) {
        this.runtime = runtime;
    }

    public String getCachedPosterPath() {
        return cachedPosterPath;
    }

    public void setCachedPosterPath(String cachedPosterPath) {
        this.cachedPosterPath = cachedPosterPath;
    }

}
